#!/usr/bin/python3
#
# The script will download and save a single
# image from the discogs.com API as an example.
# See README.md for further documentation.
#
import json
import logging
import os
import sys
import urllib.parse
import urllib.request
# from urllib.parse import urlparse
import pprint

import plugins.oauth2_compat as oauth


def authDiscogs(libPath, verbosity):
    '''
        Authenticate with Discogs online music DB before we query
    '''
    if verbosity >= 2:
        logging.info("Found the following mp3 files")

    # Your consumer key and consumer secret generated by discogs when an application is created
    # and registered . See http://www.discogs.com/settings/developers . These credentials
    # are assigned by application and remain static for the lifetime of your discogs application.
    # the consumer details below were generated for the 'discogs-oauth-example' application.
    consumer_key = os.environ.get('DISCOGS_CONSUMER_KEY')
    consumer_secret = os.environ.get('DISCOGS_CONSUMER_SECRET')
    if not consumer_key or not consumer_secret:
        sys.exit('Error: DISCOGS_CONSUMER_KEY and DISCOGS_CONSUMER_SECRET environment variables must be set.')

    # The following oauth end-points are defined by discogs.com staff. These static endpoints
    # are called at various stages of oauth handshaking.
    request_token_url = 'https://api.discogs.com/oauth/request_token'
    authorize_url = 'https://www.discogs.com/oauth/authorize'
    access_token_url = 'https://api.discogs.com/oauth/access_token'

    # A user-agent is required with Discogs API requests. Be sure to make your user-agent
    # unique, or you may get a bad response.
    user_agent = 'discogs_api_musiclint/1.0'

    # create oauth Consumer and Client objects using
    consumer = oauth.Consumer(consumer_key, consumer_secret)
    client = oauth.Client(consumer)

    # pass in your consumer key and secret to the token request URL. Discogs returns
    # an ouath_request_token as well as an oauth request_token secret.
    resp, content = client.request(request_token_url, 'POST', headers={'User-Agent': user_agent})

    # we terminate if the discogs api does not return an HTTP 200 OK. Something is
    # wrong.
    if resp['status'] != '200':
        sys.exit('Invalid response {0}.'.format(resp['status']))

    if verbosity > 0:
        print("start response: " + '\n')
        pprint.pprint(resp)
        print("end response: " + '\n')

        print("start content: " + '\n')
        pprint.pprint(content)
        print("end content: " + '\n')

    # request_token = dict(urlparse.parse_qsl(content))
    request_token = dict(urllib.parse.parse_qsl(content))

    if verbosity > 0:
        print("start token: " + '\n')
        pprint.pprint(request_token)
        print("end token: " + '\n')

    ot = request_token[b'oauth_token'].decode("utf-8")
    ots = request_token[b'oauth_token_secret'].decode("utf-8")

    if verbosity > 0:
        print("start converted token: " + '\n')
        pprint.pprint(" oauth_token string: " + ot)
        pprint.pprint(" oauth_token string: " + ots)
        print("end token: " + '\n')

        print(' == Request Token == ')
        print('    * oauth_token        = {0}'.format(ot))
        print('    * oauth_token        = {0}'.format(ots))
        
    # will act on behalf of their discogs.com account.
    # If the user accepts, discogs displays a key to the user that is used for
    # verification. The key is required in the 2nd phase of authentication.
    print('Please browse to the following URL {0}?oauth_token={1}'.format(
            authorize_url, ot))

    # Waiting for user input
    accepted = 'n'
    while accepted.lower() == 'n':
        print('\n')
        accepted = input('Have you authorized me at {0}?oauth_token={1} [y/n] :'.format(
            authorize_url, ot))

    # request the verification token from the user.
    oauth_verifier = input('Verification code :')

    # Generate objects that pass the verification key with the oauth token and oauth
    # secret to the discogs access_token_url
    token = oauth.Token(ot, ots)
    token.set_verifier(oauth_verifier)
    client = oauth.Client(consumer, token)

    resp, content = client.request(access_token_url, 'POST', headers={'User-Agent': user_agent})
    # other local store. All further requests to the discogs.com API that require authentication
    # and must be made with these access_tokens.
    # access_token = dict(urlparse.parse_qsl(content))
    access_token = dict(urllib.parse.parse_qsl(content))

    print("start access token: " + '\n')
    pprint.pprint(access_token)
    print("end access token: " + '\n')

    at = access_token[b'oauth_token'].decode("utf-8")
    ats = access_token[b'oauth_token_secret'].decode("utf-8")

    print("start converted access token: " + '\n')
    pprint.pprint(" oauth_token string: " + at)
    pprint.pprint(" oauth_token string: " + ats)
    print("end converted access token: " + '\n')

    print(' == Access Token ==')
    print('    * oauth_token        = {0}'.format(at))
    print('    * oauth_token_secret = {0}'.format(ats))
    print(' Authentication complete. Future requests must be signed with the above tokens.')
    print('\n')

    return at, ats, consumer, user_agent


def _clean_album(album):
    '''
    Remove trailing truncated parenthetical from an album name.
    e.g. "A Little South Of Sanity (Disc" -> "A Little South Of Sanity"
    '''
    if not album:
        return album
    # If there's an unclosed '(' near the end, strip from it
    idx = album.rfind('(')
    if idx != -1 and ')' not in album[idx:]:
        return album[:idx].strip()
    return album


def _discogs_search(client, user_agent, params):
    '''Execute a Discogs search and return parsed results, or None.'''
    resp, content = client.request(
        'https://api.discogs.com/database/search?' + urllib.parse.urlencode(params),
        headers={'User-Agent': user_agent}
    )
    if resp['status'] != '200':
        return None
    results = json.loads(content)
    return results if results.get('results') else None


def _pick_release(results):
    '''
    Show the user the top Discogs results and let them pick one.
    Returns the chosen release dict, or None if skipped.
    '''
    hits = results['results'][:5]
    print("\n  Discogs results:")
    for i, r in enumerate(hits):
        print(f"    [{i+1}] {r.get('title', 'Unknown')} ({r.get('year', '?')}) — {r.get('type', '')}")
    print(f"    [s] Skip / no match")

    while True:
        choice = input("  Select result [1-{0}/s]: ".format(len(hits))).strip().lower()
        if choice == 's':
            return None
        if choice.isdigit() and 1 <= int(choice) <= len(hits):
            return hits[int(choice) - 1]
        print("  Invalid choice.")


def find_releases(artist, album, track, at, ats, consumer, user_agent,
                  dir_artist=None, dir_album=None):
    '''
    Search Discogs using multiple fallback strategies and return
    (results, client, user_agent) so the caller can pick a release and
    re-pick if needed. Returns (None, None, None) if nothing is found.

    Search priority:
      1. dir_artist + dir_album  (directory hints — most reliable)
      2. tag artist  + dir_album
      3. artist + cleaned tag album
      4. artist + track title
      5. artist only
    '''
    token = oauth.Token(key=at, secret=ats)
    client = oauth.Client(consumer, token)

    clean_album = _clean_album(album)

    strategies = []
    if dir_artist and dir_album:
        strategies.append({'artist': dir_artist, 'release_title': dir_album, 'type': 'release'})
    if artist and dir_album:
        strategies.append({'artist': artist, 'release_title': dir_album, 'type': 'release'})
    if artist and clean_album:
        strategies.append({'artist': artist, 'release_title': clean_album, 'type': 'release'})
    if artist and track:
        strategies.append({'artist': artist, 'track': track, 'type': 'release'})
    if artist:
        strategies.append({'artist': artist, 'type': 'release'})

    for params in strategies:
        results = _discogs_search(client, user_agent, {k: v for k, v in params.items() if v})
        if results:
            print(f"  Discogs search: {', '.join(f'{k}={v}' for k, v in params.items() if k != 'type')}")
            return results, client, user_agent

    return None, None, None


def fetch_release(client, user_agent, release_id, track):
    '''
    Fetch full release data for a given Discogs release ID and return
    a tag dict suitable for comparison. Returns None on failure.
    '''
    resp, content = client.request(
        f'https://api.discogs.com/releases/{release_id}',
        headers={'User-Agent': user_agent}
    )

    if resp['status'] != '200':
        return None

    release = json.loads(content)

    # Strip trailing Discogs disambiguation numbers from artist names e.g. "Artist (2)"
    artists = ', '.join(
        a['name'].rstrip(' ()0123456789')
        for a in release.get('artists', [])
    )

    discogs_tags = {
        'artist': artists,
        'album':  release.get('title', ''),
        'year':   str(release.get('year', '')),
        'genre':  ', '.join(release.get('genres', [])),
        'song':   '',
        'track':  '',
    }

    # Try to match the specific track by title
    for t in release.get('tracklist', []):
        if track and track.lower() in t.get('title', '').lower():
            discogs_tags['song']  = t['title']
            discogs_tags['track'] = t.get('position', '')
            break

    return discogs_tags


def search_track(artist, album, track, at, ats, consumer, user_agent,
                 dir_artist=None, dir_album=None):
    '''
    Convenience wrapper: search, pick the first user-selected release, and
    return its tag dict. Use find_releases + _pick_release + fetch_release
    directly when re-picking between releases is needed.
    '''
    results, client, user_agent = find_releases(
        artist, album, track, at, ats, consumer, user_agent,
        dir_artist=dir_artist, dir_album=dir_album,
    )
    if not results:
        return None
    chosen = _pick_release(results)
    if not chosen:
        return None
    return fetch_release(client, user_agent, chosen['id'], track)


def queryDiscogs(libPath, verbosity):
    '''
        Query Discogs online music DB
    '''

    at, ats, consumer, user_agent = authDiscogs(libPath, verbosity)

    # We're now able to fetch an image using the application consumer key and secret,
    # along with the verified oauth token and oauth token for this user.
    token = oauth.Token(key=at,
            secret=ats)
    client = oauth.Client(consumer, token)

    # With an active auth token, we're able to reuse the client object and request
    # additional discogs authenticated endpoints, such as database search.
    resp, content = client.request('https://api.discogs.com/database/search?release_title=House+For+All&artist=Blunted+Dummies',
            headers={'User-Agent': user_agent})

    if resp['status'] != '200':
        sys.exit('Invalid API response {0}.'.format(resp['status']))

    releases = json.loads(content)
    print('\n== Search results for release_title=House For All, Artist=Blunted Dummies ==')
    for release in releases['results']:
        print('\n\t== discogs-id {id} =='.format(id=release['id']))
        print(u'\tTitle\t: {title}'.format(title=release.get('title', 'Unknown')))
        print(u'\tYear\t: {year}'.format(year=release.get('year', 'Unknown')))
        print(u'\tLabels\t: {label}'.format(label=', '.join(release.get('label',
                    ['Unknown']))))
        print(u'\tCat No\t: {catno}'.format(catno=release.get('catno', 'Unknown')))
        print(u'\tFormats\t: {fmt}'.format(fmt=', '.join(release.get('format',
                    ['Unknown']))))

    # In order to download release images, fetch the release data for id=40522
    # 40522 = http://www.discogs.com/Blunted-Dummies-House-For-All/release/40522
    resp, content = client.request('https://api.discogs.com/releases/40522',
            headers={'User-Agent': user_agent})

    if resp['status'] != '200':
        sys.exit('Unable to fetch release 40522')

    # load the JSON response content into a dictionary.
    release = json.loads(content)
    # extract the first image uri.
    image = release['images'][0]['uri']

    # The authenticated URL is genearted for you. There is no longer a need to
    # wrap the image download request in an OAuth signature.
    # build, send the HTTP GET request for the desired image.
    # DOCS: http://www.discogs.com/forum/thread/410594
    try:
        filename = os.path.basename(urllib.parse.urlparse(image).path)
        urllib.request.urlretrieve(image, filename)
    except Exception as e:
        sys.exit('Unable to download image {0}: {1}'.format(image, e))

    print(' == API image request ==')
    print('    * response status      = {0}'.format(resp['status']))
    print('    * saving image to disk = {0}'.format(image.split('/')[-1]))
